//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ClassLector
    {
        public System.Guid CL_UID { get; set; }
        public Nullable<System.Guid> C_UID { get; set; }
        public Nullable<System.Guid> D_UID { get; set; }
        public Nullable<System.Guid> L_UID { get; set; }
        public Nullable<int> CL_ID { get; set; }
        public Nullable<int> CL_Order { get; set; }
        public Nullable<int> CL_HourlyRate { get; set; }
        public string CL_Qualify { get; set; }
        public Nullable<bool> CL_IsActive { get; set; }
        public Nullable<bool> IsEvaluate { get; set; }
        public Nullable<System.Guid> CREUSER { get; set; }
        public Nullable<System.DateTime> CREDATE { get; set; }
        public Nullable<System.Guid> UPDUSER { get; set; }
        public Nullable<System.DateTime> UPDDATE { get; set; }
    }
}
