//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CELA_WEBDBEntities : DbContext
    {
        public CELA_WEBDBEntities()
            : base("name=CELA_WEBDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Book> C_Book { get; set; }
        public virtual DbSet<C_BookDetail> C_BookDetail { get; set; }
        public virtual DbSet<C_BookPublish> C_BookPublish { get; set; }
        public virtual DbSet<C_Class> C_Class { get; set; }
        public virtual DbSet<C_ClassLector> C_ClassLector { get; set; }
        public virtual DbSet<C_ClassSubject> C_ClassSubject { get; set; }
        public virtual DbSet<C_Lector> C_Lector { get; set; }
        public virtual DbSet<C_LectorAdvInfo> C_LectorAdvInfo { get; set; }
        public virtual DbSet<E_ClassUploadLog> E_ClassUploadLog { get; set; }
        public virtual DbSet<E_Evaluate> E_Evaluate { get; set; }
        public virtual DbSet<E_EvaluateDetail> E_EvaluateDetail { get; set; }
        public virtual DbSet<E_EvaluationSche> E_EvaluationSche { get; set; }
        public virtual DbSet<P_Banner> P_Banner { get; set; }
        public virtual DbSet<P_File> P_File { get; set; }
        public virtual DbSet<P_Link> P_Link { get; set; }
        public virtual DbSet<P_News> P_News { get; set; }
        public virtual DbSet<P_NewsReadLog> P_NewsReadLog { get; set; }
        public virtual DbSet<SYS_Code> SYS_Code { get; set; }
        public virtual DbSet<SYS_File> SYS_File { get; set; }
        public virtual DbSet<SYS_Menu> SYS_Menu { get; set; }
        public virtual DbSet<SYS_Power> SYS_Power { get; set; }
        public virtual DbSet<SYS_Role> SYS_Role { get; set; }
        public virtual DbSet<SYS_Unit> SYS_Unit { get; set; }
        public virtual DbSet<SYS_User> SYS_User { get; set; }
        public virtual DbSet<View_B_AssignBook> View_B_AssignBook { get; set; }
        public virtual DbSet<View_B_AssignBookEvaluateTeacher> View_B_AssignBookEvaluateTeacher { get; set; }
        public virtual DbSet<View_B_AssignBookScore> View_B_AssignBookScore { get; set; }
        public virtual DbSet<View_B_AssignBookUnLoadFile> View_B_AssignBookUnLoadFile { get; set; }
        public virtual DbSet<View_B_AssignClassEvaluate> View_B_AssignClassEvaluate { get; set; }
        public virtual DbSet<View_B_AssignClassLector> View_B_AssignClassLector { get; set; }
        public virtual DbSet<View_B_AssignClassScore> View_B_AssignClassScore { get; set; }
        public virtual DbSet<View_B_BookEvaluateTeacher> View_B_BookEvaluateTeacher { get; set; }
        public virtual DbSet<View_BookEvaluate> View_BookEvaluate { get; set; }
        public virtual DbSet<View_Bridge_C_Book> View_Bridge_C_Book { get; set; }
        public virtual DbSet<View_Bridge_C_BookPublish> View_Bridge_C_BookPublish { get; set; }
        public virtual DbSet<View_Bridge_C_Class> View_Bridge_C_Class { get; set; }
        public virtual DbSet<View_Bridge_C_ClassLector> View_Bridge_C_ClassLector { get; set; }
        public virtual DbSet<View_Bridge_C_ClassSubject> View_Bridge_C_ClassSubject { get; set; }
        public virtual DbSet<View_Bridge_C_Lector> View_Bridge_C_Lector { get; set; }
        public virtual DbSet<View_ClassEvaluate> View_ClassEvaluate { get; set; }
        public virtual DbSet<View_ClassLector> View_ClassLector { get; set; }
        public virtual DbSet<View_ClassLectorEvaluate> View_ClassLectorEvaluate { get; set; }
        public virtual DbSet<View_EvaluateDetailInfo> View_EvaluateDetailInfo { get; set; }
        public virtual DbSet<View_MenuRolePower> View_MenuRolePower { get; set; }
        public virtual DbSet<View_P_LectorClass> View_P_LectorClass { get; set; }
        public virtual DbSet<View_P_LectorClassAbstract> View_P_LectorClassAbstract { get; set; }
        public virtual DbSet<View_P_LectorEvaluate> View_P_LectorEvaluate { get; set; }
        public virtual DbSet<View_Role> View_Role { get; set; }
    }
}
