//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Banner
    {
        public System.Guid Banner_ID { get; set; }
        public int BannerType { get; set; }
        public string BannerName { get; set; }
        public string BannerURL { get; set; }
        public Nullable<System.DateTime> BannerStart { get; set; }
        public Nullable<System.DateTime> BannerEnd { get; set; }
        public Nullable<int> BannerOrder { get; set; }
        public bool BannerStatus { get; set; }
        public System.Guid CREUSER { get; set; }
        public System.DateTime CREDATE { get; set; }
        public Nullable<System.Guid> UPDUSER { get; set; }
        public Nullable<System.DateTime> UPDDATE { get; set; }
    }
}
