//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Menu
    {
        public long M_ID { get; set; }
        public string M_Type { get; set; }
        public string M_Name { get; set; }
        public long M_ParentID { get; set; }
        public int M_Level { get; set; }
        public string M_Url { get; set; }
        public int M_Order { get; set; }
        public bool M_IsActice { get; set; }
        public bool M_IsShow { get; set; }
        public System.Guid CREUSER { get; set; }
        public System.DateTime CREDATE { get; set; }
        public Nullable<System.Guid> UPDUSER { get; set; }
        public Nullable<System.DateTime> UPDDATE { get; set; }
    }
}
