//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_User
    {
        public System.Guid U_ID { get; set; }
        public System.Guid R_UID { get; set; }
        public string U_Account { get; set; }
        public string U_Password { get; set; }
        public string U_Name { get; set; }
        public string U_Email { get; set; }
        public string U_Phone { get; set; }
        public string U_Address { get; set; }
        public Nullable<byte> U_Sex { get; set; }
        public Nullable<System.DateTime> U_Birthday { get; set; }
        public string Un_ID { get; set; }
        public bool U_Status { get; set; }
        public bool isOutSide { get; set; }
        public System.Guid CREUSER { get; set; }
        public System.DateTime CREDATE { get; set; }
        public Nullable<System.Guid> UPDUSER { get; set; }
        public Nullable<System.DateTime> UPDDATE { get; set; }
    
        public virtual SYS_Role SYS_Role { get; set; }
    }
}
