//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_B_AssignBookEvaluateTeacher
    {
        public System.Guid ED_ID { get; set; }
        public System.Guid E_ID { get; set; }
        public System.Guid ES_ID { get; set; }
        public Nullable<System.Guid> Evaluate { get; set; }
        public Nullable<int> E_ScoreA { get; set; }
        public bool IsClose { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> M_ID { get; set; }
        public string M_Index { get; set; }
        public string M_Name { get; set; }
        public Nullable<System.Guid> L_UID { get; set; }
        public string L_ID { get; set; }
        public string L_NAME { get; set; }
        public Nullable<System.Guid> BP_ID { get; set; }
        public string BP_Name { get; set; }
    }
}
