//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_B_AssignClassLector
    {
        public System.Guid E_ID { get; set; }
        public int E_Year { get; set; }
        public System.Guid C_UID { get; set; }
        public string C_ID { get; set; }
        public string C_Name { get; set; }
        public System.Guid ES_ID { get; set; }
        public System.Guid CL_UID { get; set; }
        public string D_ID { get; set; }
        public string D_Name { get; set; }
        public Nullable<int> D_Hour { get; set; }
        public Nullable<System.Guid> L_UID { get; set; }
        public string L_ID { get; set; }
        public string L_NAME { get; set; }
        public int Status { get; set; }
        public bool IsSche { get; set; }
        public int ScheNum { get; set; }
        public Nullable<bool> IsPass { get; set; }
        public bool IsClose { get; set; }
        public long ChkNum { get; set; }
        public System.DateTime CREDATE { get; set; }
    }
}
