//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Bridge_C_Lector
    {
        public string L_ID { get; set; }
        public string L_NAME { get; set; }
        public Nullable<System.DateTime> L_BRITHDAY { get; set; }
        public string L_Edu { get; set; }
        public string L_EduSchool { get; set; }
        public string L_PosCode { get; set; }
        public string L_Address { get; set; }
        public string L_CPosCode { get; set; }
        public string L_CAddress { get; set; }
        public string L_Phone { get; set; }
        public string L_CellPhone { get; set; }
        public string L_Email { get; set; }
        public string L_Type { get; set; }
        public Nullable<int> L_TravelExpenses { get; set; }
        public string L_IsCheck { get; set; }
        public string L_Active { get; set; }
        public string L_Memo { get; set; }
        public string CREUSER { get; set; }
        public Nullable<System.DateTime> CREDATE { get; set; }
        public string UPDUSER { get; set; }
        public Nullable<System.DateTime> UPDDATE { get; set; }
    }
}
