//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EvaluateDetailInfo
    {
        public System.Guid ED_ID { get; set; }
        public System.Guid E_ID { get; set; }
        public Nullable<int> E_ScoreA { get; set; }
        public string M_Name { get; set; }
        public Nullable<System.Guid> MD_Publish { get; set; }
        public Nullable<System.Guid> F_MatchKey { get; set; }
    }
}
