//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_P_LectorClassAbstract
    {
        public System.Guid E_ID { get; set; }
        public System.Guid AM { get; set; }
        public System.Guid ES_ID { get; set; }
        public System.Guid BM { get; set; }
        public int Status { get; set; }
        public bool IsClose { get; set; }
        public string E_TeachAbstract { get; set; }
        public string E_TeachObject { get; set; }
        public string E_TeachSyllabus { get; set; }
        public Nullable<System.Guid> D_UID { get; set; }
        public string D_Name { get; set; }
        public string C_Name { get; set; }
        public string L_NAME { get; set; }
    }
}
