//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MenuRolePower
    {
        public System.Guid R_UID { get; set; }
        public Nullable<long> M_ID { get; set; }
        public string M_Name { get; set; }
        public Nullable<int> M_Level { get; set; }
        public Nullable<int> M_Order { get; set; }
        public string M_Type { get; set; }
        public string M_Url { get; set; }
        public Nullable<bool> CreateData { get; set; }
        public Nullable<bool> SearchData { get; set; }
        public Nullable<bool> ModifyData { get; set; }
        public Nullable<bool> DeleteData { get; set; }
        public Nullable<bool> ImportData { get; set; }
        public Nullable<bool> Exportdata { get; set; }
    }
}
