//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clea_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ClassLectorEvaluate
    {
        public System.Guid CL_UID { get; set; }
        public Nullable<System.Guid> C_UID { get; set; }
        public string C_ID { get; set; }
        public string C_Name { get; set; }
        public Nullable<System.Guid> D_UID { get; set; }
        public string D_ID { get; set; }
        public string D_Name { get; set; }
        public Nullable<System.Guid> L_UID { get; set; }
        public string L_ID { get; set; }
        public string L_NAME { get; set; }
        public Nullable<System.Guid> Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public Nullable<int> LEv_Year { get; set; }
        public Nullable<int> LEv_Type { get; set; }
    }
}
